background_image ~/Documents/~Stuff/blurred_wallpaper.png
background_tint 0.925
font_family      Hack Nerd Mono
bold_font        Hack Nerd Mono
italic_font      Hack Nerd Mono
bold_italic_font Hack Nerd Mono
font_size 12.0
confirm_os_window_close 0
shell zsh
