[Account account_1717671557_0]
Provider=kerberos
Identity=rparodi@42PARIS.FR
PresentationIdentity=rparodi@42PARIS.FR
Realm=42PARIS.FR
SessionId=33aa20ef3228c58785b5537c6661967f
IsTemporary=true
TicketingEnabled=true
